export const serviceDetails: Record<string, { description: string; services: string[]; process?: string[] }> = {
  Locksmithing: {
    description:
      'Professional locksmith services for residential and commercial properties. From emergency lockouts to advanced smart lock installations, we provide reliable security solutions.',
    services: [
      'Emergency lockout service (24/7)',
      'Rekeying locks (single or multiple doors)',
      'Smart lock installation (August, Schlage, Yale, Kwikset)',
      'Deadbolt installation and upgrade',
      'Lock repair and replacement',
      'Master key system setup',
      'Safe opening and combination reset',
      'Key duplication',
      'Commercial access control integration',
    ],
    process: ['Assess current lock system', 'Recommend best solution', 'Professional installation', 'Test and demonstrate', 'Provide key copies'],
  },
  Electrical: {
    description:
      'Licensed electrical services for homes and businesses. We handle everything from panel upgrades to EV charger installations with full code compliance.',
    services: [
      'Electrical panel upgrades and replacements',
      'Circuit breaker installation and repair',
      'Outlet and switch installation',
      'GFCI and AFCI outlet installation',
      'Lighting installation (indoor and outdoor)',
      'Ceiling fan installation',
      'EV charging station installation',
      'Electrical troubleshooting and diagnostics',
      'Whole-house surge protection',
      'Service wire upgrades',
      'Electrical safety inspections',
    ],
    process: ['Safety inspection', 'Permit acquisition (if needed)', 'Professional installation', 'Code compliance verification', 'Final testing'],
  },
  'Access Control': {
    description:
      'Modern access control systems for businesses and multi-unit properties. Keypad entry, card readers, and biometric solutions with centralized management.',
    services: [
      'Keypad entry system installation',
      'Proximity card reader systems',
      'Biometric access (fingerprint, facial recognition)',
      'Door strike and electric lock installation',
      'Intercom systems (audio and video)',
      'Mobile app access integration',
      'Centralized management software setup',
      'Access logging and reporting setup',
      'Visitor management systems',
      'Integration with existing security systems',
    ],
    process: ['Site assessment', 'System design', 'Installation', 'User setup and training', 'Ongoing support'],
  },
  'Security Systems': {
    description:
      'Complete security system installation including CCTV cameras, NVR systems, and alarm monitoring. Professional-grade equipment for homes and businesses.',
    services: [
      'CCTV camera installation (indoor and outdoor)',
      '4K and IP camera systems',
      'NVR (Network Video Recorder) setup',
      'DVR systems for analog cameras',
      'Remote viewing app setup',
      'Motion detection and alerts',
      'Night vision camera installation',
      'Door and window sensor installation',
      'Alarm system installation',
      'Monitoring service integration',
      'System maintenance and updates',
    ],
    process: ['Security assessment', 'Camera placement planning', 'Equipment installation', 'Network configuration', 'Remote access setup'],
  },
  'Fire Alarm': {
    description:
      'Fire alarm and detection system installation that meets local code requirements. Inspection-ready systems for commercial and residential properties.',
    services: [
      'Smoke detector installation and replacement',
      'Heat detector installation',
      'Fire alarm pull station installation',
      'Fire alarm control panel installation',
      'Strobe light installation',
      'Sprinkler system integration',
      'Code-compliant system design',
      'Annual inspection and testing',
      'Battery backup systems',
      'Emergency communication systems',
      'Fire alarm monitoring service setup',
    ],
    process: ['Code review', 'System design', 'Installation', 'Inspection coordination', 'Certification documentation'],
  },
  'Data/Low Voltage': {
    description:
      'Structured cabling and low-voltage wiring for networking, audio/video, and telecommunications. Clean, organized installations with proper labeling.',
    services: [
      'Cat6 and Cat6a Ethernet cable installation',
      'Network rack and patch panel installation',
      'Wall jack installation (data ports)',
      'Wireless access point installation',
      'Wi-Fi coverage optimization',
      'Structured media center setup',
      'Audio/video cable routing',
      'Security camera cable installation',
      'Intercom system wiring',
      'Speaker and audio system wiring',
      'Cable management and labeling',
      'Testing and certification',
    ],
    process: ['Site survey', 'Cable routing plan', 'Professional installation', 'Termination and testing', 'Documentation'],
  },
  'TV Mounting': {
    description:
      'Professional TV mounting with hidden wiring and cable management. Secure installations on any wall type with proper load considerations.',
    services: [
      'TV wall mounting (all sizes)',
      'Full-motion, tilt, or fixed mount options',
      'In-wall cable concealment',
      'Soundbar installation and mounting',
      'Surround sound speaker placement',
      'Cable management solutions',
      'Outlet relocation behind TV',
      'Mounting on brick, concrete, or drywall',
      'Multiple TV installations',
      'TV calibration and setup',
      'Removal and reinstallation services',
    ],
    process: ['Wall assessment', 'Mount selection', 'Secure installation', 'Cable management', 'TV setup and testing'],
  },
  'Electronic Repairs': {
    description:
      'Expert repairs for consumer electronics and nano devices. We fix TVs (non-broken screens), cellphones, tablets, PCs/laptops, gaming devices, and custom builds with professional soldering and diagnostic services.',
    services: [
      'Cellphone repairs (charging ports, batteries, cameras, speakers)',
      'Tablet repairs (connectors, charging, audio, motherboard issues)',
      'TV repairs (non-broken screens - power issues, main boards, backlight)',
      'PC and laptop repairs (motherboards, power issues, connectors)',
      'Gaming console repairs (PS4, PS5, Xbox, Nintendo Switch)',
      'Custom PC builds and upgrades',
      'Board-level soldering (micro-soldering for small components)',
      'Component-level diagnostics and testing',
      'Battery replacement and repair',
      'Charging port repair and replacement',
      'Audio/video component repair',
      'Power supply diagnostics and repair',
      'Circuit board trace repair',
      'Data recovery from damaged devices',
    ],
    process: ['Device diagnostic testing', 'Issue identification', 'Part sourcing', 'Professional repair', 'Quality testing and verification'],
  },
};

